# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------

project = "奇遇淘客"
copyright = "2022, 奇遇科技"
author = "奇遇科技"

# The full version, including alpha/beta/rc tags
release = ""

# -- General configuration ---------------------------------------------------


# for sitemap remove lang and version
html_baseurl = "https://tbk.qiyutech.tech"
sitemap_url_scheme = "{link}"

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    # for sitemap
    "sphinx_sitemap",
    "sphinx_copybutton",
    # for custom 404 page
    "notfound.extension",
    # for better experience
    # https://sphinxcontrib-images.readthedocs.io/en/latest/
    "sphinxcontrib.images",
]

# not found extension
# https://sphinx-notfound-page.readthedocs.io/en/latest/configuration.html#confval-notfound_no_urls_prefix
notfound_no_urls_prefix = True

# sphinxcontrib.images config
# https://sphinxcontrib-images.readthedocs.io/en/latest/
images_config = {"override_image_directive": False}

# sphinx.ext.todo
# https://www.sphinx-doc.org/en/master/usage/extensions/todo.html#confval-todo_include_todos
todo_include_todos = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "zh_CN"

# 搜索支持中文
html_search_language = "zh_CN"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "furo"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# 不允许查看源代码
html_show_sourcelink = False

# 设置 logo
html_logo = "_static/img/logo.svg"

# doc
# https://www.sphinx-doc.org/en/master/usage/configuration.html
# foru 不需要配置这些
# html_sidebars = {
#    "**": [
#        "globaltoc.html",
#        "searchbox.html",
#    ]
# }
